#!/bin/sh

#----------------#
# set gtk+ theme #
#----------------#
# 您可以使用 echo $XCURSOR_SIZE 和 echo $XCURSOR_THEME去检查它们的值。
# seat seat0 xcursor_theme 'Catppuccin-cursor' 36
# usage: import-gsettings
config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
if [ ! -f "$config" ]; then exit 1; fi

gnome_schema="org.gnome.desktop.interface"
gtk_theme="$(grep 'gtk-theme-name' "$config" | sed 's/.*\s*=\s*//')"
icon_theme="$(grep 'gtk-icon-theme-name' "$config" | sed 's/.*\s*=\s*//')"
cursor_theme="$(grep 'gtk-cursor-theme-name' "$config" | sed 's/.*\s*=\s*//')"
font_name="$(grep 'gtk-font-name' "$config" | sed 's/.*\s*=\s*//')"
gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" font-name "$font_name"
gsettings set org.gnome.desktop.input-sources show-all-sources true
# gsettings set $gnome-schema cursor-size "$cursor-size"
# gsettings set $gnome-schema color-scheme "$gtk-color-scheme"
