live_config_reload = true

import = [
"~/.config/alacritty/keybindings.toml"
]

[shell]
  program = "pwsh"
  args = ["-NoLogo", "-NoProfile"]

[env]
TERM = "xterm-256color"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[window]
opacity = 0.85
dynamic_padding = false
decorations = "buttonless"

[window.padding]
x = 18
y = 16

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true
